[[redirects]]
from = "/"
to = "/index.html"
status = 200

[[redirects]]
from = "/portfolio"
to = "/portfolio.html"
status = 200

[[redirects]]
from = "/about"
to = "/about.html"
status = 200

[[redirects]]
from = "/contact"
to = "/contact.html"
status = 200

[[redirects]]
from = "/services"
to = "/service.html"
status = 200
